const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'
const FETCH_PRANKS_SUCCESS = 'FETCH_PRANKS_SUCCESS'
const SEARCH_PRANKS_SUCCESS = 'SEARCH_PRANKS_SUCCESS'


const types = {
    FETCH_CATEGORIES_REQUEST,
    FETCH_CATEGORIES_SUCCESS,
    FETCH_CATEGORIES_FAILURE,
    FETCH_PRANKS_SUCCESS,
    SEARCH_PRANKS_SUCCESS
}

export default types